name: api_client
description: Client gọi HTTP API, dùng model từ shared.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  http: ^1.2.0
  shared:
    path: ../shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
