CREATE TYPE "measure_unit" AS ENUM (
  'gram',
  'liter',
  'piece'
);

CREATE TYPE "meal_type" AS ENUM (
  'breakfast',
  'lunch',
  'dinner',
  'snack'
);

CREATE TYPE "gender" AS ENUM (
  'male',
  'female',
  'other'
);

-- Khoá ngoại khai báo ngay tại cột, không DEFERRABLE. Mặc định chặn xoá dòng cha đang được tham chiếu;
-- chỉ dòng con "thuộc về" cha (recipe_items, meal_items) mới ON DELETE CASCADE.

CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "birth_date" date,
  "gender" gender,
  "height_cm" decimal,
  "weight_g" decimal,
  "daily_calorie_goals" decimal,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "auths" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL UNIQUE,
  "password_hash" varchar NOT NULL,
  "user_id" integer NOT NULL UNIQUE REFERENCES "users" ("id")
);

CREATE TABLE "user_health_records" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "weight_g" decimal NOT NULL,
  "recorded_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "products" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "product_nutritions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL REFERENCES "products" ("id"),
  "measure_unit" measure_unit NOT NULL,
  "measurement" decimal NOT NULL CHECK (measurement > 0),
  "calories" decimal NOT NULL CHECK (calories >= 0),
  "price" decimal CHECK (price >= 0)
);

CREATE TABLE "recipes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "name" varchar NOT NULL,
  "detail_recipe" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "recipe_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipe_id" integer NOT NULL REFERENCES "recipes" ("id") ON DELETE CASCADE,
  "product_nutrition_id" integer NOT NULL REFERENCES "product_nutritions" ("id"),
  "quantity" decimal NOT NULL CHECK (quantity > 0)
);

CREATE TABLE "meals" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "meal_type" meal_type NOT NULL,
  "eaten_at" timestamp NOT NULL
);

CREATE TABLE "meal_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_id" integer NOT NULL REFERENCES "meals" ("id") ON DELETE CASCADE,
  "recipe_id" integer NOT NULL REFERENCES "recipes" ("id"),
  "portion" decimal NOT NULL DEFAULT 1 CHECK (portion > 0)
);

CREATE UNIQUE INDEX ON "product_nutritions" ("product_id", "measure_unit", "measurement");

CREATE UNIQUE INDEX ON "recipe_items" ("recipe_id", "product_nutrition_id");

CREATE INDEX ON "recipes" ("user_id");

CREATE INDEX ON "meals" ("user_id", "eaten_at");

CREATE INDEX ON "user_health_records" ("user_id", "recorded_at");

CREATE INDEX ON "recipe_items" ("product_nutrition_id");

CREATE INDEX ON "meal_items" ("recipe_id");

-- updated_at tự cập nhật mỗi khi UPDATE dòng, code không cần tự gán.
CREATE FUNCTION "set_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "recipes_set_updated_at" BEFORE UPDATE ON "recipes"
  FOR EACH ROW EXECUTE FUNCTION "set_updated_at"();

CREATE TRIGGER "user_health_records_set_updated_at" BEFORE UPDATE ON "user_health_records"
  FOR EACH ROW EXECUTE FUNCTION "set_updated_at"();
