CREATE TYPE "measure_unit" AS ENUM (
  'gram',
  'liter',
  'piece'
);

CREATE TYPE "meal_type" AS ENUM (
  'breakfast',
  'lunch',
  'dinner',
  'snack'
);

CREATE TYPE "gender" AS ENUM (
  'male',
  'female',
  'other'
);

-- Cột timestamp không kèm múi giờ lưu giờ địa phương của người dùng (Việt Nam). DEFAULT now() lấy theo múi giờ
-- của phiên kết nối, nên cố định múi giờ của DB để giá trị mặc định không lệch 7 tiếng khi Postgres chạy UTC
-- (image Docker mặc định). Áp dụng cho các phiên kết nối mở sau migration này.
DO $$
BEGIN
  EXECUTE 'ALTER DATABASE ' || quote_ident(current_database()) || ' SET timezone TO ''Asia/Ho_Chi_Minh''';
END
$$;

-- Khoá ngoại khai báo ngay tại cột, không DEFERRABLE. Mặc định chặn xoá dòng cha đang được tham chiếu;
-- chỉ dòng con "thuộc về" cha (recipe_items, meal_items) mới ON DELETE CASCADE.

CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "birth_date" date,
  "gender" gender,
  "height_cm" decimal CHECK (height_cm > 0),
  "weight_g" decimal CHECK (weight_g > 0),
  "daily_calorie_goals" decimal CHECK (daily_calorie_goals > 0),
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "auths" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL UNIQUE,
  "password_hash" varchar NOT NULL,
  "user_id" integer NOT NULL UNIQUE REFERENCES "users" ("id")
);

CREATE TABLE "user_health_records" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "weight_g" decimal NOT NULL CHECK (weight_g > 0),
  "recorded_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "products" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "product_nutritions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL REFERENCES "products" ("id"),
  "measure_unit" measure_unit NOT NULL,
  "measurement" decimal NOT NULL CHECK (measurement > 0),
  "calories" decimal NOT NULL CHECK (calories >= 0),
  "price" decimal CHECK (price >= 0)
);

CREATE TABLE "recipes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "name" varchar NOT NULL,
  "detail_recipe" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "recipe_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipe_id" integer NOT NULL REFERENCES "recipes" ("id") ON DELETE CASCADE,
  "product_nutrition_id" integer NOT NULL REFERENCES "product_nutritions" ("id"),
  "quantity" decimal NOT NULL CHECK (quantity > 0)
);

CREATE TABLE "meals" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "users" ("id"),
  "meal_type" meal_type NOT NULL,
  "eaten_at" timestamp NOT NULL
);

CREATE TABLE "meal_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meal_id" integer NOT NULL REFERENCES "meals" ("id") ON DELETE CASCADE,
  "recipe_id" integer NOT NULL REFERENCES "recipes" ("id"),
  "portion" decimal NOT NULL DEFAULT 1 CHECK (portion > 0)
);

-- Index đặt tên rõ để migration sau DROP/ALTER không phải đoán tên Postgres tự sinh.
CREATE UNIQUE INDEX "product_nutritions_product_unit_measurement_key"
  ON "product_nutritions" ("product_id", "measure_unit", "measurement");

CREATE UNIQUE INDEX "recipe_items_recipe_nutrition_key" ON "recipe_items" ("recipe_id", "product_nutrition_id");

CREATE INDEX "recipe_items_product_nutrition_id_idx" ON "recipe_items" ("product_nutrition_id");

-- Danh sách công thức: WHERE user_id = ? ORDER BY updated_at DESC, id DESC.
CREATE INDEX "recipes_user_id_updated_at_idx" ON "recipes" ("user_id", "updated_at" DESC, "id" DESC);

CREATE INDEX "meals_user_id_eaten_at_idx" ON "meals" ("user_id", "eaten_at");

CREATE INDEX "meal_items_meal_id_idx" ON "meal_items" ("meal_id");

CREATE INDEX "meal_items_recipe_id_idx" ON "meal_items" ("recipe_id");

CREATE INDEX "user_health_records_user_id_recorded_at_idx" ON "user_health_records" ("user_id", "recorded_at");

-- updated_at tự cập nhật mỗi khi UPDATE dòng, code không cần tự gán.
CREATE FUNCTION "set_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "recipes_set_updated_at" BEFORE UPDATE ON "recipes"
  FOR EACH ROW EXECUTE FUNCTION "set_updated_at"();

CREATE TRIGGER "user_health_records_set_updated_at" BEFORE UPDATE ON "user_health_records"
  FOR EACH ROW EXECUTE FUNCTION "set_updated_at"();
