name: app
description: Ứng dụng Flutter cho iOS, Android và Web.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  api_client:
    path: ../../packages/api_client
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^16.0.0
  shared:
    path: ../../packages/shared

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
