name: api
description: Máy chủ API Dart Frog.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  dart_frog: ^1.1.0
  postgres: ^3.5.0
  shared:
    path: ../../packages/shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
